name: C++ Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up C++ environment
        run: sudo apt-get install g++

      - name: Find and compile all C++ files
        run: |
          find problems -name "main.cpp" | while read file; do
            # Compile each main.cpp to an executable with a unique name
            dir=$(dirname "$file")
            g++ "$file" -o "${dir}/output"
          done
