name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y g++

    - name: Compile
      run: g++ -o output_file main.cpp

    - name: Run Program (Optional)
      run: ./output_file
