name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Check if configure script is present
      - name: List files
        run: ls -la

      # Ensure the configure script is executable and run it
      - name: Make configure executable
        run: chmod +x ./configure

      - name: Run configure
        run: ./configure

      - name: make
        run: make

      - name: make check
        run: make check

      - name: make distcheck
        run: make distcheck
